# Generated by Django 5.2.17 on 2026-09-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tax_inclusive',
            field=models.BooleanField(default=False),
        ),
    ]
