# Generated by Django 5.2.17 on 2026-09-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(db_index=True)),
                ('note', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI')], default='CASH', max_length=10)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('EXPENSE', 'Expense'), ('RETURN', 'Return')], db_index=True, max_length=12)),
                ('ref_type', models.CharField(blank=True, max_length=40)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['account_type', 'date'], name='ledger_ledg_account_e54411_idx'), models.Index(fields=['ref_type', 'ref_id'], name='ledger_ledg_ref_typ_b39215_idx')],
            },
        ),
    ]
