# Generated by Django 5.2.17 on 2026-09-29 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='POS Billing', max_length=180)),
                ('address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('logo', models.ImageField(blank=True, upload_to='shop/')),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('footer_note', models.CharField(blank=True, max_length=240)),
                ('default_tax', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('paper_size', models.CharField(choices=[('80MM', '80mm thermal'), ('A4', 'A4')], default='80MM', max_length=8)),
                ('allow_negative_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
