# Generated by Django 5.2.17 on 2026-09-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_no', models.CharField(db_index=True, max_length=40, unique=True)),
                ('reason', models.TextField()),
                ('refund_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CREDIT', 'Customer credit')], max_length=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='billing.bill')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('restock', models.BooleanField(default=True)),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='billing.billitem')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_returns.salereturn')),
            ],
        ),
    ]
